//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by xsd.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndreiPopescu.CharazayPlus.Model
{
  using System.Xml.Serialization;
  using System;
  using BrightIdeasSoftware;
  using AndreiPopescu.CharazayPlus.Utils;
  using System.Diagnostics;
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using System.Collections.Generic;


  #region up to v 1.1.6.9
  
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  [Obsolete("Replaced by CT_Bookmarks")]
  public partial class TLPlayers
  {
    /// <remarks/>
    [XmlElement("TLPlayer")]
    public TLPlayer[] TLPlayer
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  [Obsolete("Replaced by CT_Bookmark")]
  public partial class TLPlayer
  {

    #region inference

    //[OLVColumn(DisplayIndex = 0, IsEditable = false, Width = 35, MinimumWidth = 25, MaximumWidth = 45, Title = "Position")]
    //public PlayerPosition Pos
    //{
    //  get { return (PlayerPosition)System.Enum.Parse(typeof(PlayerPosition), Position); }
    //}

    /// <remarks/>
    public string Deadline
    {
      get;
      set;
    }

    #endregion

    #region serialized fields

    [OLVColumn(DisplayIndex = 2, IsEditable = false, Width = 50, MinimumWidth = 35, MaximumWidth = 80, Title = "Age / Value Index", AspectToStringFormat = "{0:F02}", ToolTipText = "age value index")]
    public double AgeValueIndex { get; set; }

    /// <remarks/>
    public string Position { get; set; }

    /// <remarks/>
    [OLVColumn(DisplayIndex = 4, IsEditable = false, Width = 50, MinimumWidth = 35, MaximumWidth = 70, Title = "Profitability", AspectToStringFormat = "{0:F02}")]
    public double Profitability { get; set; }


    /// <remarks/>
    public ulong PlayerId { get; set; }


    /// <remarks/>
    [OLVColumn(DisplayIndex = 1, IsEditable = false, Width = 130, MinimumWidth = 100, MaximumWidth = 190, Title = "Player")]
    public string Name { get; set; }

    /// <remarks/>
    [OLVColumn(DisplayIndex = 3, IsEditable = true, Width = 70, MinimumWidth = 50, MaximumWidth = 100, Title = "Price", AspectToStringFormat = "{0:N0}")]
    public uint Price { get; set; }

    [OLVColumn(DisplayIndex = 5, IsEditable = true, Width = 100, MinimumWidth = 75, MaximumWidth = 150, Title = "Deadline", AspectToStringFormat = "{0:yyyy.MM.dd HH:mm}")]
    public System.DateTime DeadLine
    {
      get
      {
        return String.IsNullOrWhiteSpace(Deadline) ? DateTime.MaxValue : System.DateTime.Parse(Deadline);
      }
    }

    [OLVColumn(DisplayIndex = 6,
      IsEditable = true,
      Width = 80,
      MinimumWidth = 60,
      MaximumWidth = 140,
      Title = "Importance",
      ToolTipText = "How important is this transfer?")]
    public byte Importance { get; set; }

    #endregion

  }
  #endregion

  #region from version 1.1.6.10

  /// <remarks>
  /// by modifying element names the size of the serialized xml dropped to half the original
  /// </remarks>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlRootAttribute("root", Namespace = "", IsNullable = false)]
  public partial class CT_TransferBookmarks
  {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("p")]
    //public CT_TransferBookmark[] Items { get; set; }
    public List<CT_TransferBookmark> Items { get; set; }
  }


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  public partial class CT_TransferBookmark
  {
    [OLVColumn(DisplayIndex = 0, IsEditable = false, Width = 35, MinimumWidth = 25, MaximumWidth = 45, Title = "Position")]
    [XmlElement("e")]
    public ST_PlayerPositionEnum Position { get; set; }

    [OLVColumn(DisplayIndex = 1, IsEditable = false, Width = 130, MinimumWidth = 100, MaximumWidth = 190, Title = "Player")]
    [XmlElement("n")]
    public string Name { get; set; }

    [OLVColumn(DisplayIndex = 3, Width = 70, MinimumWidth = 50, MaximumWidth = 100
      , Title = "Price", AspectToStringFormat = "{0:N0}", IsEditable = true)]
    [XmlElement("x")]
    public uint Price { get; set; }

    [OLVColumn(DisplayIndex = 5, Width = 100, MinimumWidth = 75, MaximumWidth = 150
      , Title = "Deadline", AspectToStringFormat = "{0:yyyy.MM.dd HH:mm}", IsEditable = true)]
    [XmlElement("d")]
    public System.DateTime Deadline { get; set; }

    [OLVColumn(DisplayIndex = 2, IsEditable = false, Width = 50, MinimumWidth = 35, MaximumWidth = 80
      , Title = "Age / Value Index", AspectToStringFormat = "{0:F02}", ToolTipText = "age value index")]
    [XmlElement("v")]
    public double AgeValueIndex { get; set; }

    [OLVColumn(DisplayIndex = 4, Width = 50, MinimumWidth = 35, MaximumWidth = 70
      , Title = "Profitability", AspectToStringFormat = "{0:F02}", IsEditable = false)]
    [XmlElement("r")]
    public double Profitability { get; set; }

    [XmlElement("id")]
    public ulong PlayerId { get; set; }

     [OLVColumn(DisplayIndex = 6, Width = 80, MinimumWidth = 60, MaximumWidth = 140
       , IsEditable = true, Title = "Importance", ToolTipText = "How important is this transfer?")]
    [XmlElement("m")]
    public ST_Importance Importance { get; set; }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  public enum ST_PlayerPositionEnum
  {

    /// <remarks/>
    PG = 0,

    /// <remarks/>
    SG = 1,

    /// <remarks/>
    SF = 2,

    /// <remarks/>
    PF = 3,

    /// <remarks/>
    C = 4,

    /// <remarks/>
    Unknown = 255,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  public enum ST_Importance
  {

    /// <remarks/>
    High = 3,

    /// <remarks/>
    Medium = 2,

    /// <remarks/> 
    Small = 1,

    /// <remarks/>
    None = 0,
  }
  
  #endregion


}
