//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Model
{
  using System;
  using System.Xml.Serialization;
  using System.Collections.Generic;
  using System.Diagnostics;
  using System.ComponentModel;


  /// <remarks/>

  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false, ElementName = "development")]
  public partial class Development
  {
    [XmlElement("playerItem")]
    public List<PlayerDevelopment> PlayerItems { get; set; }
  }

  /// <remarks/>

  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class PlayerDevelopment
  {
    /// <remarks/>
    [XmlElement("v")]
    public List<CT_VALUE_AT_DATE> ItemValues { get; set; }

    /// <remarks/>
    [XmlAttribute]
    public uint id { get; set; }

    /// <remarks/>
    [XmlAttribute]
    public string name { get; set; }

    [XmlAttribute]
    public string surname { get; set; }

    [XmlAttribute]
    [DefaultValue(false)]
    public bool active { get; set; }
  }

  /// <remarks/>

  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlRoot("v", Namespace = "", IsNullable = false)]
  public partial class CT_VALUE_AT_DATE
  {

    /// <remarks/>
    [XmlAttribute(AttributeName = "t")]
    public ST_VALUE_TYPE Type { get; set; }

    /// <remarks/>
    [XmlAttribute(AttributeName = "d")]
    public string DateString { get; set; }

    /// <remarks/>
    [XmlTextAttribute()]
    public string Value { get; set; }
  }

  /// <remarks/>

  [Serializable]
  public enum ST_VALUE_TYPE
  {

    /// <remarks/>
    age,

    /// <remarks/>
    h,

    /// <remarks/>
    w,

    /// <remarks/>
    def,

    /// <remarks/>
    exp,

    /// <remarks/>
    p1,

    /// <remarks/>
    p2,

    /// <remarks/>
    p3,

    /// <remarks/>
    dri,

    /// <remarks/>
    spe,

    /// <remarks/>
    ftw,

    /// <remarks/>
    reb,

    /// <remarks/>
    pas,

    /// <remarks/>
    inj,

    /// <remarks/>
    fatg,

    /// <remarks/>
    form,

    /// <remarks/>
    fame,

    /// <remarks/>
    si,

    /// <remarks/>
    sal,
  }
}
