#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndreiPopescu.CharazayPlus.Objects
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CharazayTM")]
	public partial class TransferHistoryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHistory(History instance);
    partial void UpdateHistory(History instance);
    partial void DeleteHistory(History instance);
    #endregion
		
		public TransferHistoryDataContext() : 
				base(global::AndreiPopescu.CharazayPlus.Properties.Settings.Default.CharazayTM_TDS_ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TransferHistoryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransferHistoryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransferHistoryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransferHistoryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<History> Histories
		{
			get
			{
				return this.GetTable<History>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCreateTableMapping")]
		public ISingleResult<spCreateTableMappingResult> spCreateTableMapping()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spCreateTableMappingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateTM")]
		public void spUpdateTM()
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertC")]
		public int spInsertC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(4,2)")] System.Nullable<decimal> agevalueindex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(6,2)")] System.Nullable<decimal> price)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), age, agevalueindex, price);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertF")]
		public int spInsertF([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(4,2)")] System.Nullable<decimal> agevalueindex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(6,2)")] System.Nullable<decimal> price)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), age, agevalueindex, price);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertG")]
		public int spInsertG([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(4,2)")] System.Nullable<decimal> agevalueindex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(6,2)")] System.Nullable<decimal> price)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), age, agevalueindex, price);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRemoveDuplicates")]
		public int spRemoveDuplicates([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(4,2)")] System.Nullable<decimal> agevalueindex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(6,2)")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> posid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> day)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), age, agevalueindex, price, posid, day);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.History")]
	public partial class History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _Age;
		
		private decimal _AgeValueIndex;
		
		private decimal _Price;
		
		private char _PosId;
		
		private System.DateTime _Day;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAgeChanging(byte value);
    partial void OnAgeChanged();
    partial void OnAgeValueIndexChanging(decimal value);
    partial void OnAgeValueIndexChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnPosIdChanging(char value);
    partial void OnPosIdChanged();
    partial void OnDayChanging(System.DateTime value);
    partial void OnDayChanged();
    #endregion
		
		public History()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeValueIndex", DbType="Decimal(4,2) NOT NULL", IsPrimaryKey=true)]
		public decimal AgeValueIndex
		{
			get
			{
				return this._AgeValueIndex;
			}
			set
			{
				if ((this._AgeValueIndex != value))
				{
					this.OnAgeValueIndexChanging(value);
					this.SendPropertyChanging();
					this._AgeValueIndex = value;
					this.SendPropertyChanged("AgeValueIndex");
					this.OnAgeValueIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(6,2) NOT NULL", IsPrimaryKey=true)]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosId", DbType="Char(1) NOT NULL", IsPrimaryKey=true)]
		public char PosId
		{
			get
			{
				return this._PosId;
			}
			set
			{
				if ((this._PosId != value))
				{
					this.OnPosIdChanging(value);
					this.SendPropertyChanging();
					this._PosId = value;
					this.SendPropertyChanged("PosId");
					this.OnPosIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spCreateTableMappingResult
	{
		
		private short _week;
		
		private byte _age;
		
		private string _Position;
		
		private decimal _v11;
		
		private decimal _v10;
		
		private System.Nullable<decimal> _r;
		
		public spCreateTableMappingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week", DbType="SmallInt NOT NULL")]
		public short week
		{
			get
			{
				return this._week;
			}
			set
			{
				if ((this._week != value))
				{
					this._week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="TinyInt NOT NULL")]
		public byte age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_v11", DbType="Decimal(5,2) NOT NULL")]
		public decimal v11
		{
			get
			{
				return this._v11;
			}
			set
			{
				if ((this._v11 != value))
				{
					this._v11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_v10", DbType="Decimal(5,2) NOT NULL")]
		public decimal v10
		{
			get
			{
				return this._v10;
			}
			set
			{
				if ((this._v10 != value))
				{
					this._v10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> r
		{
			get
			{
				return this._r;
			}
			set
			{
				if ((this._r != value))
				{
					this._r = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
