//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Utils
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class TLPlayers
  {

    private TLPlayer[] tLPlayerField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TLPlayer")]
    public TLPlayer[] TLPlayer
    {
      get
      {
        return this.tLPlayerField;
      }
      set
      {
        this.tLPlayerField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class TLPlayer
  {

    private string positionField;
    public PlayerPosition Pos
    {
      get { return (PlayerPosition)System.Enum.Parse(typeof(PlayerPosition), positionField); }
    }

    private string nameField;

    private uint priceField;

    //private string dateField;
    //public System.DateTime DateTime { get { return System.DateTime.Parse(dateField); } }

    private string deadlineField;
    public System.DateTime DeadLine { get { return System.DateTime.Parse(deadlineField); } }

    private decimal valueIndexField;

    private decimal profitabilityField;

    private decimal totalField;

    private decimal defField;

    private decimal offField;

    private decimal ofAbField;

    private decimal shootField;

    private decimal rebField;

    private decimal rebOField;

    private decimal rebDField;

    /// <remarks/>
    public string Position
    {
      get
      {
        return this.positionField;
      }
      set
      {
        this.positionField = value;
      }
    }

    /// <remarks/>
    public string Name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    public uint Price
    {
      get
      {
        return this.priceField;
      }
      set
      {
        this.priceField = value;
      }
    }

    ///// <remarks/>
    //public string Date {
    //    get {
    //        return this.dateField;
    //    }
    //    set {
    //        this.dateField = value;
    //    }
    //}

    /// <remarks/>
    public string Deadline
    {
      get
      {
        return this.deadlineField;
      }
      set
      {
        this.deadlineField = value;
      }
    }

    /// <remarks/>
    public decimal ValueIndex
    {
      get
      {
        return this.valueIndexField;
      }
      set
      {
        this.valueIndexField = value;
      }
    }

    /// <remarks/>
    public decimal Profitability
    {
      get
      {
        return this.profitabilityField;
      }
      set
      {
        this.profitabilityField = value;
      }
    }

    /// <remarks/>
    public decimal Total
    {
      get
      {
        return this.totalField;
      }
      set
      {
        this.totalField = value;
      }
    }

    /// <remarks/>
    public decimal Def
    {
      get
      {
        return this.defField;
      }
      set
      {
        this.defField = value;
      }
    }

    /// <remarks/>
    public decimal Off
    {
      get
      {
        return this.offField;
      }
      set
      {
        this.offField = value;
      }
    }

    /// <remarks/>
    public decimal OfAb
    {
      get
      {
        return this.ofAbField;
      }
      set
      {
        this.ofAbField = value;
      }
    }

    /// <remarks/>
    public decimal Shoot
    {
      get
      {
        return this.shootField;
      }
      set
      {
        this.shootField = value;
      }
    }

    /// <remarks/>
    public decimal Reb
    {
      get
      {
        return this.rebField;
      }
      set
      {
        this.rebField = value;
      }
    }

    /// <remarks/>
    public decimal RebO
    {
      get
      {
        return this.rebOField;
      }
      set
      {
        this.rebOField = value;
      }
    }

    /// <remarks/>
    public decimal RebD
    {
      get
      {
        return this.rebDField;
      }
      set
      {
        this.rebDField = value;
      }
    }
  }
}
