//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2
{
  using System.Xml.Serialization;
  using System.Diagnostics;
  using System.CodeDom.Compiler;
  using System;
  using System.ComponentModel;


  public partial class charazay
  {

    /// <remarks/>
    [XmlArrayItem("coach", IsNullable = false)]
    public charazayCoach[] coaches
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayCoach
  {

    /// <remarks/>
    public charazayCoachBasic basic
    {
      get;
      set;
    }

    /// <remarks/>
    public charazayCoachSkills skills
    {
      get;
      set;
    }

    /// <remarks/>
    public uint price
    {
      get;
      set;
    }

    /// <remarks/>
    public uint salary
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint id
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte countryid
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint teamid
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayCoachBasic
  {


    /// <remarks/>
    public string name
    {
      get;
      set;
    }

    /// <remarks/>
    public string surname
    {
      get;
      set;
    }

    /// <remarks/>
    public byte age
    {
      get;
      set;
    }

    /// <remarks/>
    public byte height
    {
      get;
      set;
    }

    /// <remarks/>
    public byte weight
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayCoachSkills
  {


    /// <remarks/>
    public byte defence
    {
      get;
      set;
    }

    /// <remarks/>
    public byte freethrow
    {
      get;
      set;
    }

    /// <remarks/>
    public byte twopoint
    {
      get;
      set;
    }

    /// <remarks/>
    public byte threepoint
    {
      get;
      set;
    }

    /// <remarks/>
    public byte dribling
    {
      get;
      set;
    }

    /// <remarks/>
    public byte speed
    {
      get;
      set;
    }

    /// <remarks/>
    public byte footwork
    {
      get;
      set;
    }

    /// <remarks/>
    public byte rebounds
    {
      get;
      set;
    }

    /// <remarks/>
    public byte passing
    {
      get;
      set;
    }

    /// <remarks/>
    public byte experience
    {
      get;
      set;
    }
  }
}
