//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2 {
    using System.Xml.Serialization;
    
    
    public partial class charazay {
        
        private charazayCoach[] coachesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("coach", IsNullable=false)]
        public charazayCoach[] coaches {
            get {
                return this.coachesField;
            }
            set {
                this.coachesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayCoach {
        
        private charazayCoachBasic basicField;
        
        private charazayCoachSkills skillsField;
        
        private uint priceField;
        
        private uint salaryField;
        
        private uint idField;
        
        private byte countryidField;
        
        private uint teamidField;
        
        /// <remarks/>
        public charazayCoachBasic basic {
            get {
                return this.basicField;
            }
            set {
                this.basicField = value;
            }
        }
        
        /// <remarks/>
        public charazayCoachSkills skills {
            get {
                return this.skillsField;
            }
            set {
                this.skillsField = value;
            }
        }
        
        /// <remarks/>
        public uint price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public uint salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint teamid {
            get {
                return this.teamidField;
            }
            set {
                this.teamidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayCoachBasic {
        
        private string nameField;
        
        private string surnameField;
        
        private byte ageField;
        
        private byte heightField;
        
        private byte weightField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public byte age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public byte height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public byte weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayCoachSkills {
        
        private byte defenceField;
        
        private byte freethrowField;
        
        private byte twopointField;
        
        private byte threepointField;
        
        private byte driblingField;
        
        private byte speedField;
        
        private byte footworkField;
        
        private byte reboundsField;
        
        private byte passingField;
        
        private byte experienceField;
        
        /// <remarks/>
        public byte defence {
            get {
                return this.defenceField;
            }
            set {
                this.defenceField = value;
            }
        }
        
        /// <remarks/>
        public byte freethrow {
            get {
                return this.freethrowField;
            }
            set {
                this.freethrowField = value;
            }
        }
        
        /// <remarks/>
        public byte twopoint {
            get {
                return this.twopointField;
            }
            set {
                this.twopointField = value;
            }
        }
        
        /// <remarks/>
        public byte threepoint {
            get {
                return this.threepointField;
            }
            set {
                this.threepointField = value;
            }
        }
        
        /// <remarks/>
        public byte dribling {
            get {
                return this.driblingField;
            }
            set {
                this.driblingField = value;
            }
        }
        
        /// <remarks/>
        public byte speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        public byte footwork {
            get {
                return this.footworkField;
            }
            set {
                this.footworkField = value;
            }
        }
        
        /// <remarks/>
        public byte rebounds {
            get {
                return this.reboundsField;
            }
            set {
                this.reboundsField = value;
            }
        }
        
        /// <remarks/>
        public byte passing {
            get {
                return this.passingField;
            }
            set {
                this.passingField = value;
            }
        }
        
        /// <remarks/>
        public byte experience {
            get {
                return this.experienceField;
            }
            set {
                this.experienceField = value;
            }
        }
    }
}
