//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2 {
    using System.Xml.Serialization;
  using AndreiPopescu.CharazayPlus.Utils;
    
    
   public partial class charazay {
        
        private charazayCountry countryField;
        
        /// <remarks/>
        public charazayCountry country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayCountry {
        
        private string nameField;
        
        private string flagField;
        
        private charazayCountryDivision[] divisionField;
        
        private charazayCountryCountry_info country_infoField;
        
        private byte idField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("division")]
        public charazayCountryDivision[] division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        public charazayCountryCountry_info country_info {
            get {
                return this.country_infoField;
            }
            set {
                this.country_infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayCountryDivision {
        
        private string nameField;
        
        private ushort idField;
        
        private byte levelField;
        
        private byte lhField;
        
        private byte countryidField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte lh {
            get {
                return this.lhField;
            }
            set {
                this.lhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayCountryCountry_info {
        
        private charazayCountryCountry_infoNtcoach ntcoachField;
        
        private charazayCountryCountry_infoU21ntcoach u21ntcoachField;
        
        private charazayCountryCountry_infoU18ntcoach u18ntcoachField;
        
        private string activeField;
        
        private ushort usersField;
        
        private ushort teamsField;

        private ushort waitingField;

        private ushort supportersField;
        
        /// <remarks/>
        public charazayCountryCountry_infoNtcoach ntcoach {
            get {
                return this.ntcoachField;
            }
            set {
                this.ntcoachField = value;
            }
        }
        
        /// <remarks/>
        public charazayCountryCountry_infoU21ntcoach u21ntcoach {
            get {
                return this.u21ntcoachField;
            }
            set {
                this.u21ntcoachField = value;
            }
        }
        
        /// <remarks/>
        public charazayCountryCountry_infoU18ntcoach u18ntcoach {
            get {
                return this.u18ntcoachField;
            }
            set {
                this.u18ntcoachField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort users
        {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort teams {
            get {
                return this.teamsField;
            }
            set {
                this.teamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort waiting
        {
            get {
                return this.waitingField;
            }
            set {
                this.waitingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort supporters
        {
            get {
                return this.supportersField;
            }
            set {
                this.supportersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayCountryCountry_infoNtcoach {
        
        private user userField;
        
        private string botField;
        
        /// <remarks/>
        public user user
        {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bot {
            get {
                return this.botField;
            }
            set {
                this.botField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [System.ComponentModel.TypeConverterAttribute(typeof(Xsd2CountryUserTypeConverter))]
    [System.ComponentModel.DescriptionAttribute("Expand to see country user info")]
    public partial class user
    {

      private string nameField;

      private uint idField;

      private string supporterField;
      
      private uint registeredField;

      private uint last_activeField;

      private ushort teamidField;

      private byte countryidField;

      [System.ComponentModel.ReadOnly(true)]
      public string name
      {
        get
        {
          return this.nameField;
        }
        set
        {
          this.nameField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      [System.ComponentModel.ReadOnly(true)]
      public uint id
      {
        get
        {
          return this.idField;
        }
        set
        {
          this.idField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      [System.ComponentModel.ReadOnly(true)]
      public string supporter
      {
        get
        {
          return this.supporterField;
        }
        set
        {
          this.supporterField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      [System.ComponentModel.Browsable(false)]
      public uint registered
      {
        get
        {
          return this.registeredField;
        }
        set
        {
          this.registeredField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      [System.ComponentModel.Browsable(false)]
      public uint last_active
      {
        get
        {
          return this.last_activeField;
        }
        set
        {
          this.last_activeField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      [System.ComponentModel.ReadOnly(true)]
      public ushort teamid
      {
        get
        {
          return this.teamidField;
        }
        set
        {
          this.teamidField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      [System.ComponentModel.ReadOnly(true)]
      public byte countryid
      {
        get
        {
          return this.countryidField;
        }
        set
        {
          this.countryidField = value;
        }
      }

      public override string ToString()
      {
        return string.Format("{0}|{1}|{2}|{3}|{4}|{5}|{6}"
          , name, id, supporter, registered, last_active, teamid, countryid);        
      }

      public static explicit operator user(string s)
      {
        user u = new user();
        string [] ars = s.Split(new char[] { '|' });
        u.name = ars[0];
        u.id = uint.Parse(ars[1]);
        u.supporter = ars[2];
        u.registered = uint.Parse(ars[3]);
        u.last_active = uint.Parse(ars[4]);
        u.teamid = ushort.Parse(ars[5]);
        u.countryid = byte.Parse(ars[6]);

        return u;
      }

      [System.ComponentModel.ReadOnly (true)]
      public System.DateTime RegisteredDate { get { return Compute.EstimatedDateTime(registeredField); } }
      [System.ComponentModel.ReadOnly(true)]
      public System.DateTime LastActiveDate { get { return Compute.EstimatedDateTime(last_activeField); } }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayCountryCountry_infoU21ntcoach {

      private user userField;
        
        private string botField;
        
        /// <remarks/>
        public user user
        {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bot {
            get {
                return this.botField;
            }
            set {
                this.botField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayCountryCountry_infoU18ntcoach {

      private user userField;
        
        private string botField;
        
        /// <remarks/>
        public user user
        {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bot {
            get {
                return this.botField;
            }
            set {
                this.botField = value;
            }
        }
    }
}
