//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2 {
    using System.Xml.Serialization;
  using System.Diagnostics;
  using System.CodeDom.Compiler;
  using System;
  using System.ComponentModel;
    
    
    public partial class charazay {
        
        /// <remarks/>
        [XmlArrayItem("round", IsNullable=false)]
        public charazayRound[] schedule {
          get;
          set;
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class charazayRound {
        
        /// <remarks/>
        public charazayRoundMatch match {
          get;
          set;
        }
        
        /// <remarks/>
        [XmlAttribute]
        public byte number {
          get;
          set;
        }
        
        /// <remarks/>
        [XmlAttribute]
        public uint date {
          get;
          set;
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class charazayRoundMatch {
        
        /// <remarks/>
        [XmlAttribute]
        public uint id {
          get;
          set;
        }
    }
}
