//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2
{
  using System.Xml.Serialization;
  using System.Diagnostics;
  using System.ComponentModel;
  using System;
  using System.CodeDom.Compiler;

  public partial class charazay
  {

    /// <remarks/>
    public charazayEconomy economy
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayEconomy
  {

    /// <remarks/>
    public charazayEconomyEconomy_week economy_week
    {
      get;
      set;
    }

    /// <remarks/>
    public charazayEconomyEconomy_season economy_season
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayEconomyEconomy_week
  {

    /// <remarks/>
    public income income
    {
      get;
      set;
    }

    /// <remarks/>
    public expences expences
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class income
  {

    /// <remarks/>
    public uint sponsor
    {
      get;
      set;
    }

    /// <remarks/>
    public uint tickets
    {
      get;
      set;
    }

    /// <remarks/>
    public uint sales
    {
      get;
      set;
    }

    /// <remarks/>
    public uint other
    {
      get;
      set;
    }

    /// <remarks/>
    public uint merchandise
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class expences
  {

    /// <remarks/>
    public uint salary
    {
      get;
      set;
    }

    /// <remarks/>
    public uint staff
    {
      get;
      set;
    }

    /// <remarks/>
    public uint buys
    {
      get;
      set;
    }

    /// <remarks/>
    public uint maintenance
    {
      get;
      set;
    }

    /// <remarks/>
    public uint facility
    {
      get;
      set;
    }

    /// <remarks/>
    public uint other
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayEconomyEconomy_season
  {

    /// <remarks/>
    public income income
    {
      get;
      set;
    }

    /// <remarks/>
    public expences expences
    {
      get;
      set;
    }
  }
}
