//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2 {
    using System.Xml.Serialization;
    
    
    public partial class charazay {
        
        private charazayEconomy economyField;
        
        /// <remarks/>
        public charazayEconomy economy {
            get {
                return this.economyField;
            }
            set {
                this.economyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayEconomy {
        
        private charazayEconomyEconomy_week economy_weekField;
        
        private charazayEconomyEconomy_season economy_seasonField;
        
        /// <remarks/>
        public charazayEconomyEconomy_week economy_week {
            get {
                return this.economy_weekField;
            }
            set {
                this.economy_weekField = value;
            }
        }
        
        /// <remarks/>
        public charazayEconomyEconomy_season economy_season {
            get {
                return this.economy_seasonField;
            }
            set {
                this.economy_seasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayEconomyEconomy_week {
        
        private income incomeField;
        
        private expences expencesField;
        
        /// <remarks/>
        public income income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
            }
        }
        
        /// <remarks/>
        public expences expences {
            get {
                return this.expencesField;
            }
            set {
                this.expencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class income 
    {
        
        private uint sponsorField;
        
        private uint ticketsField;
        
        private uint salesField;
        
        private uint otherField;
        
        private uint merchandiseField;
        
        /// <remarks/>
        public uint sponsor {
            get {
                return this.sponsorField;
            }
            set {
                this.sponsorField = value;
            }
        }
        
        /// <remarks/>
        public uint tickets {
            get {
                return this.ticketsField;
            }
            set {
                this.ticketsField = value;
            }
        }
        
        /// <remarks/>
        public uint sales {
            get {
                return this.salesField;
            }
            set {
                this.salesField = value;
            }
        }
        
        /// <remarks/>
        public uint other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
            }
        }
        
        /// <remarks/>
        public uint merchandise {
            get {
                return this.merchandiseField;
            }
            set {
                this.merchandiseField = value;
            }
        }

        public uint Total { get { return sponsor + tickets + sales + other + merchandise; } }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class expences {
        
        private uint salaryField;
        
        private uint staffField;
        
        private uint buysField;
        
        private uint maintenanceField;
        
        private uint facilityField;
        
        private uint otherField;
        
        /// <remarks/>
        public uint salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
            }
        }
        
        /// <remarks/>
        public uint staff {
            get {
                return this.staffField;
            }
            set {
                this.staffField = value;
            }
        }
        
        /// <remarks/>
        public uint buys {
            get {
                return this.buysField;
            }
            set {
                this.buysField = value;
            }
        }
        
        /// <remarks/>
        public uint maintenance {
            get {
                return this.maintenanceField;
            }
            set {
                this.maintenanceField = value;
            }
        }
        
        /// <remarks/>
        public uint facility {
            get {
                return this.facilityField;
            }
            set {
                this.facilityField = value;
            }
        }
        
        /// <remarks/>
        public uint other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
            }
        }

        public uint Total { get { return salary + staff+ buys + other + maintenance+facility; } }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayEconomyEconomy_season {
        
        private income incomeField;
        
        private expences expencesField;
        
        /// <remarks/>
        public income income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
            }
        }
        
        /// <remarks/>
        public expences expences {
            get {
                return this.expencesField;
            }
            set {
                this.expencesField = value;
            }
        }
    }
}
