//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2
{
  using BrightIdeasSoftware;
  using System.Xml.Serialization;
  using System.Diagnostics;
  using System.CodeDom.Compiler;
  using System;
  using System.ComponentModel;

  ///// <remarks/>
  //[GeneratedCode("xsd", "4.0.30319.1")]
  //[Serializable]
  //[DebuggerStepThrough]
  //[DesignerCategory("code")]
  //[XmlType(AnonymousType=true)]
  //[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
  public partial class charazay
  {

    /// <remarks/>
    public match match
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class match
  {

    /// <remarks/>
    public teams teams
    {
      get;
      set;
    }

    /// <remarks/>
    public stats stats
    {
      get;
      set;
    }

    /// <remarks/>
    public bballs bballs
    {
      get;
      set;
    }

    /// <remarks/>
    public lineup lineup
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint id
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint date
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte round
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte season
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint spectators
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint vips
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public string played
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte homescore
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte awayscore
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte type
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint leagueid
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class teams
  {

    /// <remarks/>
    public uint hometeam
    {
      get;
      set;
    }

    /// <remarks/>
    public string hometeamname
    {
      get;
      set;
    }

    /// <remarks/>
    public uint awayteam
    {
      get;
      set;
    }

    /// <remarks/>
    public string awayteamname
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class rating
  {


    [OLVColumn("Pt", DisplayIndex = 2, ToolTipText = "Points", Width = 39)]
    public byte points
    {
      get;
      set;
    }

    [OLVColumn("Ro", DisplayIndex = 3, ToolTipText = "Offensive Rebounds", Width = 39)]
    public byte o_reb
    {
      get;
      set;
    }

    [OLVColumn("Rd", DisplayIndex = 4, ToolTipText = "Defensive Rebounds", Width = 39)]
    public byte d_reb
    {
      get;
      set;
    }

    [OLVColumn("To", DisplayIndex = 5, ToolTipText = "Turnovers", Width = 39)]
    public byte to
    {
      get;
      set;
    }

    [OLVColumn("As", DisplayIndex = 6, ToolTipText = "Assists", Width = 39)]
    public byte assist
    {
      get;
      set;
    }

    [OLVColumn("Bl", DisplayIndex = 7, ToolTipText = "Blocks", Width = 39)]
    public byte blocks
    {
      get;
      set;
    }

    [OLVColumn("St", DisplayIndex = 8, ToolTipText = "Steals", Width = 39)]
    public byte steals
    {
      get;
      set;
    }

    [OLVColumn("Fo", DisplayIndex = 9, ToolTipText = "Fouls", Width = 39)]
    public byte fouls
    {
      get;
      set;
    }

    [OLVColumn("Ftm", DisplayIndex = 10, ToolTipText = "Freethrows made", Width = 39)]
    public byte ft_m
    {
      get;
      set;
    }

    [OLVColumn("Fta", DisplayIndex = 11, ToolTipText = "Freethrows attempted", Width = 39)]
    public byte ft_a
    {
      get;
      set;
    }

    [OLVColumn("2pm", DisplayIndex = 12, ToolTipText = "2p made", Width = 39)]
    public byte pt2_m
    {
      get;
      set;
    }

    [OLVColumn("2pa", DisplayIndex = 13, ToolTipText = "2p attempted", Width = 39)]
    public byte pt2_a
    {
      get;
      set;
    }

    [OLVColumn("3pm", DisplayIndex = 14, ToolTipText = "3p made", Width = 39)]
    public byte pt3_m
    {
      get;
      set;
    }

    [OLVColumn("3pa", DisplayIndex = 15, ToolTipText = "3p attempted", Width = 39)]
    public byte pt3_a
    {
      get;
      set;
    }

    [OLVColumn("Pld", DisplayIndex = 16, ToolTipText = "Played", Width = 39)]
    public byte pld
    {
      get;
      set;
    }

    [OLVColumn("Rtg", DisplayIndex = 1, ToolTipText = "Rating", Width = 39)]
    public sbyte rtg
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint playerid
    {
      get;
      set;
    }

    [OLVColumn("Player", DisplayIndex = 0, Width = 130)]
    [XmlAttribute]
    public string name
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class bball
  {

    /// <remarks/>
    [XmlAttribute]
    public uint playerid
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public decimal bballs
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class stats
  {

    /// <remarks/>
    [XmlArrayItem("rating", IsNullable = false)]
    public rating[] home
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlArrayItem("rating", IsNullable = false)]
    public rating[] away
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class bballs
  {

    /// <remarks/>
    [XmlArrayItem("bball", IsNullable = false)]
    public bball[] home
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlArrayItem("bball", IsNullable = false)]
    public bball[] away
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class lineup
  {
    /// <remarks/>
    public lineupHome home
    {
      get;
      set;
    }

    /// <remarks/>
    public lineupAway away
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class lineupHome
  {
    /// <remarks/>
    public first first
    {
      get;
      set;
    }

    /// <remarks/>
    public second second
    {
      get;
      set;
    }

    /// <remarks/>
    public third third
    {
      get;
      set;
    }

    /// <remarks/>
    public forth forth
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class first
  {
    /// <remarks/>
    public uint pg
    {
      get;
      set;
    }

    /// <remarks/>
    public uint sg
    {
      get;
      set;
    }

    /// <remarks/>
    public uint sf
    {
      get;
      set;
    }

    /// <remarks/>
    public uint pf
    {
      get;
      set;
    }

    /// <remarks/>
    public uint c
    {
      get;
      set;
    }
  }

  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class second
  {
    /// <remarks/>
    public uint pg
    {
      get;
      set;
    }

    /// <remarks/>
    public uint sg
    {
      get;
      set;
    }

    /// <remarks/>
    public uint sf
    {
      get;
      set;
    }

    /// <remarks/>
    public uint pf
    {
      get;
      set;
    }

    /// <remarks/>
    public uint c
    {
      get;
      set;
    }
  }

  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class third
  {
    /// <remarks/>
    public uint pg
    {
      get;
      set;
    }

    /// <remarks/>
    public uint sg
    {
      get;
      set;
    }

    /// <remarks/>
    public uint sf
    {
      get;
      set;
    }

    /// <remarks/>
    public uint pf
    {
      get;
      set;
    }

    /// <remarks/>
    public uint c
    {
      get;
      set;
    }
  }

  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class forth
  {
    /// <remarks/>
    public uint pg
    {
      get;
      set;
    }

    /// <remarks/>
    public uint sg
    {
      get;
      set;
    }

    /// <remarks/>
    public uint sf
    {
      get;
      set;
    }

    /// <remarks/>
    public uint pf
    {
      get;
      set;
    }

    /// <remarks/>
    public uint c
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class lineupAway
  {

    /// <remarks/>
    public first first
    {
      get;
      set;
    }

    /// <remarks/>
    public second second
    {
      get;
      set;
    }

    /// <remarks/>
    public third third
    {
      get;
      set;
    }

    /// <remarks/>
    public forth forth
    {
      get;
      set;
    }
  }
}
