//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2 {
    using System.Xml.Serialization;
    
    
    public partial class charazay {
        
        private charazayPlayer playerField;
        
        /// <remarks/>
        public charazayPlayer player {
            get {
                return this.playerField;
            }
            set {
                this.playerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayPlayer {
        
        private charazayPlayerBasic basicField;
        
        private charazayPlayerSkills skillsField;
        
        private charazayPlayerStatus statusField;
        
        private uint idField;
        
        private string transferField;
        
        private string ntField;
        
        private string u21ntField;
        
        private string u18ntField;
        
        private uint promoted_onField;
        
        private string dlField;
        
        private byte countryidField;
        
        private string teamidField;
        
        private byte traininggroupField;
        
        /// <remarks/>
        public charazayPlayerBasic basic {
            get {
                return this.basicField;
            }
            set {
                this.basicField = value;
            }
        }
        
        /// <remarks/>
        public charazayPlayerSkills skills {
            get {
                return this.skillsField;
            }
            set {
                this.skillsField = value;
            }
        }
        
        /// <remarks/>
        public charazayPlayerStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transfer {
            get {
                return this.transferField;
            }
            set {
                this.transferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nt {
            get {
                return this.ntField;
            }
            set {
                this.ntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string u21nt {
            get {
                return this.u21ntField;
            }
            set {
                this.u21ntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string u18nt {
            get {
                return this.u18ntField;
            }
            set {
                this.u18ntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint promoted_on {
            get {
                return this.promoted_onField;
            }
            set {
                this.promoted_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dl {
            get {
                return this.dlField;
            }
            set {
                this.dlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string teamid {
            get {
                return this.teamidField;
            }
            set {
                this.teamidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte traininggroup {
            get {
                return this.traininggroupField;
            }
            set {
                this.traininggroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayPlayerBasic {
        
        private string nameField;
        
        private string surnameField;
        
        private byte ageField;
        
        private byte heightField;
        
        private decimal weightField;
        
        private charazayPlayerBasicNumber numberField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public byte age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public byte height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public decimal weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public charazayPlayerBasicNumber number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayPlayerBasicNumber {
        
        private string showField;
        
        private byte valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string show {
            get {
                return this.showField;
            }
            set {
                this.showField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public byte Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayPlayerSkills {
        
        private byte defenceField;
        
        private byte freethrowField;
        
        private byte twopointField;
        
        private byte threepointField;
        
        private byte driblingField;
        
        private byte speedField;
        
        private byte footworkField;
        
        private byte reboundsField;
        
        private byte passingField;
        
        private byte experienceField;
        
        /// <remarks/>
        public byte defence {
            get {
                return this.defenceField;
            }
            set {
                this.defenceField = value;
            }
        }
        
        /// <remarks/>
        public byte freethrow {
            get {
                return this.freethrowField;
            }
            set {
                this.freethrowField = value;
            }
        }
        
        /// <remarks/>
        public byte twopoint {
            get {
                return this.twopointField;
            }
            set {
                this.twopointField = value;
            }
        }
        
        /// <remarks/>
        public byte threepoint {
            get {
                return this.threepointField;
            }
            set {
                this.threepointField = value;
            }
        }
        
        /// <remarks/>
        public byte dribling {
            get {
                return this.driblingField;
            }
            set {
                this.driblingField = value;
            }
        }
        
        /// <remarks/>
        public byte speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        public byte footwork {
            get {
                return this.footworkField;
            }
            set {
                this.footworkField = value;
            }
        }
        
        /// <remarks/>
        public byte rebounds {
            get {
                return this.reboundsField;
            }
            set {
                this.reboundsField = value;
            }
        }
        
        /// <remarks/>
        public byte passing {
            get {
                return this.passingField;
            }
            set {
                this.passingField = value;
            }
        }
        
        /// <remarks/>
        public byte experience {
            get {
                return this.experienceField;
            }
            set {
                this.experienceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayPlayerStatus {
        
        private byte injuredField;
        
        private byte fatigueField;
        
        private byte formField;
        
        private byte fameField;
        
        private uint siField;
        
        private uint salaryField;
        
        /// <remarks/>
        public byte injured {
            get {
                return this.injuredField;
            }
            set {
                this.injuredField = value;
            }
        }
        
        /// <remarks/>
        public byte fatigue {
            get {
                return this.fatigueField;
            }
            set {
                this.fatigueField = value;
            }
        }
        
        /// <remarks/>
        public byte form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
            }
        }
        
        /// <remarks/>
        public byte fame {
            get {
                return this.fameField;
            }
            set {
                this.fameField = value;
            }
        }
        
        /// <remarks/>
        public uint si {
            get {
                return this.siField;
            }
            set {
                this.siField = value;
            }
        }
        
        /// <remarks/>
        public uint salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
            }
        }
    }
}
