//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2
{

  using System.Xml.Serialization;
  using System.Diagnostics;
  using System.CodeDom.Compiler;
  using System;
  using System.ComponentModel;


  public partial class charazay
  {

    public charazayPlayer player
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayPlayer
  {


    public charazayPlayerBasic basic
    {
      get;
      set;
    }

    /// <remarks/>
    public charazayPlayerSkills skills
    {
      get;
      set;
    }

    /// <remarks/>
    public charazayPlayerStatus status
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint id
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public string transfer
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public string nt
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public string u21nt
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public string u18nt
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint promoted_on
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public string dl
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte countryid
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public string teamid
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte traininggroup
    {
      get;
      set;
    }

    #region national team caps

    [XmlAttribute]
    public ushort u19cap
    {
      get;
      set;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool u19capSpecified
    {
      get;
      set;
    }


    [XmlAttribute]
    public ushort u21cap
    {
      get;
      set;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool u21capSpecified
    {
      get;
      set;
    }

    [XmlAttribute]
    public ushort ntcap
    {
      get;
      set;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ntcapSpecified
    {
      get;
      set;
    }
    #endregion
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayPlayerBasic
  {


    public string name
    {
      get;
      set;
    }

    /// <remarks/>
    public string surname
    {
      get;
      set;
    }

    /// <remarks/>
    public byte age
    {
      get;
      set;
    }

    /// <remarks/>
    public byte height
    {
      get;
      set;
    }

    /// <remarks/>
    public decimal weight
    {
      get;
      set;
    }

    /// <remarks/>
    public charazayPlayerBasicNumber number
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayPlayerBasicNumber
  {

    [XmlAttribute]
    public string show
    {
      get;
      set;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public byte Value
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayPlayerSkills
  {


    public byte defence
    {
      get;
      set;
    }

    /// <remarks/>
    public byte freethrow
    {
      get;
      set;
    }

    /// <remarks/>
    public byte twopoint
    {
      get;
      set;
    }

    /// <remarks/>
    public byte threepoint
    {
      get;
      set;
    }

    /// <remarks/>
    public byte dribling
    {
      get;
      set;
    }

    /// <remarks/>
    public byte speed
    {
      get;
      set;
    }

    /// <remarks/>
    public byte footwork
    {
      get;
      set;
    }

    /// <remarks/>
    public byte rebounds
    {
      get;
      set;
    }

    /// <remarks/>
    public byte passing
    {
      get;
      set;
    }

    /// <remarks/>
    public byte experience
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayPlayerStatus
  {


    public byte injured
    {
      get;
      set;
    }

    /// <remarks/>
    public int fatigue
    {
      get;
      set;
    }

    /// <remarks/>
    public byte form
    {
      get;
      set;
    }

    /// <remarks/>
    public byte fame
    {
      get;
      set;
    }

    /// <remarks/>
    public uint si
    {
      get;
      set;
    }

    /// <remarks/>
    public uint salary
    {
      get;
      set;
    }
  }
}
