//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2 
{
    using System.Xml.Serialization;
    
   public partial class charazay 
   {
        
        private charazayPlayer playerField;
        
        /// <remarks/>
        public charazayPlayer player 
        {
            get {
                return this.playerField;
            }
            set {
                this.playerField = value;
            }
        }
    }    
    
}
