//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2
{
  using System.Xml.Serialization;

  public partial class charazay
  {

    [XmlArrayItem("player", IsNullable = false)]
    public charazayPlayer[] players
    {
      get;
      set;
    }
  }
}
