//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2 {
    using System.Xml.Serialization;
    
    
    public partial class charazay {
        
        private match[] matchesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("match", IsNullable=false)]
        public match[] matches {
            get {
                return this.matchesField;
            }
            set {
                this.matchesField = value;
            }
        }
    }

    #region Duplicated with Match.xsd
    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    //public partial class charazayMatch {

    //    private charazayMatchTeams teamsField;
    //    public string HomeTeam { get { return teamsField.hometeamname; } }
    //    public string AwayTeam { get { return teamsField.awayteamname; } }

    //    private uint idField;

    //    private uint dateField;
    //    public System.DateTime Deadline { get { return Common.Compute.EstimatedDateTime(dateField); } }

    //    private byte roundField;

    //    private byte seasonField;

    //    private ushort spectatorsField;

    //    private ushort vipsField;

    //    private string playedField;
    //    public bool Played { get { return playedField == "yes"; } }

    //    private byte homescoreField;

    //    private byte awayscoreField;

    //    private byte typeField;
    //    public string MatchType { get { return System.Enum.GetName ( typeof(Common.MatchType) ,
    //      (Common.MatchType)typeField); } }

    //    private ushort leagueidField;

    //    private bool leagueidFieldSpecified;

    //    private ushort nationalcupidField;

    //    private bool nationalcupidFieldSpecified;

    //    /// <remarks/>
    //    public charazayMatchTeams teams {
    //        get {
    //            return this.teamsField;
    //        }
    //        set {
    //            this.teamsField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public uint id {
    //        get {
    //            return this.idField;
    //        }
    //        set {
    //            this.idField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public uint date {
    //        get {
    //            return this.dateField;
    //        }
    //        set {
    //            this.dateField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public byte round {
    //        get {
    //            return this.roundField;
    //        }
    //        set {
    //            this.roundField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public byte season {
    //        get {
    //            return this.seasonField;
    //        }
    //        set {
    //            this.seasonField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public ushort spectators {
    //        get {
    //            return this.spectatorsField;
    //        }
    //        set {
    //            this.spectatorsField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public ushort vips {
    //        get {
    //            return this.vipsField;
    //        }
    //        set {
    //            this.vipsField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string played {
    //        get {
    //            return this.playedField;
    //        }
    //        set {
    //            this.playedField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public byte homescore {
    //        get {
    //            return this.homescoreField;
    //        }
    //        set {
    //            this.homescoreField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public byte awayscore {
    //        get {
    //            return this.awayscoreField;
    //        }
    //        set {
    //            this.awayscoreField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public byte type {
    //        get {
    //            return this.typeField;
    //        }
    //        set {
    //            this.typeField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public ushort leagueid {
    //        get {
    //            return this.leagueidField;
    //        }
    //        set {
    //            this.leagueidField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlIgnoreAttribute()]
    //    public bool leagueidSpecified {
    //        get {
    //            return this.leagueidFieldSpecified;
    //        }
    //        set {
    //            this.leagueidFieldSpecified = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public ushort nationalcupid {
    //        get {
    //            return this.nationalcupidField;
    //        }
    //        set {
    //            this.nationalcupidField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlIgnoreAttribute()]
    //    public bool nationalcupidSpecified {
    //        get {
    //            return this.nationalcupidFieldSpecified;
    //        }
    //        set {
    //            this.nationalcupidFieldSpecified = value;
    //        }
    //    }
    //}

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    //public partial class charazayMatchTeams {

    //    private ushort hometeamField;

    //    private string hometeamnameField;

    //    private ushort awayteamField;

    //    private string awayteamnameField;

    //    /// <remarks/>
    //    public ushort hometeam {
    //        get {
    //            return this.hometeamField;
    //        }
    //        set {
    //            this.hometeamField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string hometeamname {
    //        get {
    //            return this.hometeamnameField;
    //        }
    //        set {
    //            this.hometeamnameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public ushort awayteam {
    //        get {
    //            return this.awayteamField;
    //        }
    //        set {
    //            this.awayteamField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string awayteamname {
    //        get {
    //            return this.awayteamnameField;
    //        }
    //        set {
    //            this.awayteamnameField = value;
    //        }
    //    }
    //} 
    #endregion
}
