//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2 {
    using System.Xml.Serialization;
    
    
    public partial class charazay {
        
        private charazayTeam teamField;
        
        /// <remarks/>
        public charazayTeam team {
            get {
                return this.teamField;
            }
            set {
                this.teamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayTeam {
        
        private string nameField;
        
        private charazayTeamTeam_info team_infoField;
        
        private uint idField;
        
        private byte countryidField;
        
        private uint useridField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public charazayTeamTeam_info team_info {
            get {
                return this.team_infoField;
            }
            set {
                this.team_infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayTeamTeam_info {
        
        private charazayTeamTeam_infoFanclub fanclubField;
        
        private charazayTeamTeam_infoTraining trainingField;
        
        private byte chemistryField;
        
        private uint divisionidField;
        
        private uint arenaidField;
        
        private uint rivalField;
        
        /// <remarks/>
        public charazayTeamTeam_infoFanclub fanclub {
            get {
                return this.fanclubField;
            }
            set {
                this.fanclubField = value;
            }
        }
        
        /// <remarks/>
        public charazayTeamTeam_infoTraining training {
            get {
                return this.trainingField;
            }
            set {
                this.trainingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte chemistry {
            get {
                return this.chemistryField;
            }
            set {
                this.chemistryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint divisionid {
            get {
                return this.divisionidField;
            }
            set {
                this.divisionidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint arenaid {
            get {
                return this.arenaidField;
            }
            set {
                this.arenaidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint rival {
            get {
                return this.rivalField;
            }
            set {
                this.rivalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayTeamTeam_infoFanclub {
        
        private string nameField;
        
        private byte moodField;
        
        private uint fansField;
        
        private byte levelField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte mood {
            get {
                return this.moodField;
            }
            set {
                this.moodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint fans {
            get {
                return this.fansField;
            }
            set {
                this.fansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayTeamTeam_infoTraining {
        
        private string group1Field;
        
        private string group2Field;
        
        /// <remarks/>
        public string group1 {
            get {
                return this.group1Field;
            }
            set {
                this.group1Field = value;
            }
        }
        
        /// <remarks/>
        public string group2 {
            get {
                return this.group2Field;
            }
            set {
                this.group2Field = value;
            }
        }
    }
}
