//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2
{

  using System.Xml.Serialization;
  using System.Diagnostics;
  using System.CodeDom.Compiler;
  using System;
  using System.ComponentModel;

  public partial class charazay
  {

    public charazayTeam team
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayTeam
  {

    public string name
    {
      get;
      set;
    }

    /// <remarks/>
    public charazayTeamTeam_info team_info
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint id
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte countryid
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint userid
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayTeamTeam_info
  {

    public charazayTeamTeam_infoFanclub fanclub
    {
      get;
      set;
    }

    /// <remarks/>
    public charazayTeamTeam_infoTraining training
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte chemistry
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint divisionid
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint arenaid
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint rival
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayTeamTeam_infoFanclub
  {

    public string name
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte mood
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint fans
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte level
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayTeamTeam_infoTraining
  {

    public string group1
    {
      get;
      set;
    }

    /// <remarks/>
    public string group2
    {
      get;
      set;
    }
  }
}
