//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndreiPopescu.CharazayPlus.Xsd2
{

  using System.Xml.Serialization;
  using System.Diagnostics;
  using System.CodeDom.Compiler;
  using System;
  using System.ComponentModel;

  public partial class charazay
  {

    [XmlArrayItem("transfer", IsNullable = false)]
    public charazayTransfer[] team_transfers
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayTransfer
  {

    public uint sellteam
    {
      get;
      set;
    }

    /// <remarks/>
    public uint buyteam
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint playerid
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint date
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint si
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint price
    {
      get;
      set;
    }
  }
}
