//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2 {
    using System.Xml.Serialization;
    
    
    public partial class charazay {
        
        private charazayTransfer[] team_transfersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("transfer", IsNullable=false)]
        public charazayTransfer[] team_transfers {
            get {
                return this.team_transfersField;
            }
            set {
                this.team_transfersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class charazayTransfer {
        
        private ushort sellteamField;
        
        private ushort buyteamField;
        
        private uint playeridField;
        
        private uint dateField;
                
        private uint siField;
        
        private uint priceField;
        
        /// <remarks/>
        public ushort sellteam {
            get {
                return this.sellteamField;
            }
            set {
                this.sellteamField = value;
            }
        }
        
        /// <remarks/>
        public ushort buyteam {
            get {
                return this.buyteamField;
            }
            set {
                this.buyteamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint playerid {
            get {
                return this.playeridField;
            }
            set {
                this.playeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint si {
            get {
                return this.siField;
            }
            set {
                this.siField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
}
