//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by m tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.Xsd2
{
  using System;
  using System.Xml.Serialization;  
  using System.Diagnostics;
  using System.ComponentModel;
  using System.CodeDom.Compiler;


  public partial class charazay
  {

    /// <remarks/>
    public charazayUser user
    {
      get;
      set;
    }
  }

  /// <remarks/>
  [GeneratedCode("xsd", "4.0.30319.1")]
  [Serializable]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true)]
  public partial class charazayUser
  {

    public string name
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint id
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public string supporter
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint registered
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint last_active
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public uint teamid
    {
      get;
      set;
    }

    /// <remarks/>
    [XmlAttribute]
    public byte countryid
    {
      get;
      set;
    }
  }
}
