//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AndreiPopescu.CharazayPlus.Xsd2
{
  using System.Xml.Serialization;

  // 
  // This source code was auto-generated by xsd, Version=4.0.30319.1.
  // 


  /// <remarks/>
  
  public partial class charazay
  {

    private charazayUser userField;

    /// <remarks/>
    public charazayUser user
    {
      get
      {
        return this.userField;
      }
      set
      {
        this.userField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  public partial class charazayUser
  {

    private string nameField;

    private ushort idField;

    private string supporterField;

    private uint registeredField;

    private uint last_activeField;

    private ushort teamidField;

    private byte countryidField;

    /// <remarks/>
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string supporter
    {
      get
      {
        return this.supporterField;
      }
      set
      {
        this.supporterField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint registered
    {
      get
      {
        return this.registeredField;
      }
      set
      {
        this.registeredField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint last_active
    {
      get
      {
        return this.last_activeField;
      }
      set
      {
        this.last_activeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort teamid
    {
      get
      {
        return this.teamidField;
      }
      set
      {
        this.teamidField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte countryid
    {
      get
      {
        return this.countryidField;
      }
      set
      {
        this.countryidField = value;
      }
    }
  }
}