//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AndreiPopescu.CharazayPlus.XsdMerge 
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class charazay {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("arena", typeof(arena))]
        [System.Xml.Serialization.XmlElementAttribute("coaches", typeof(coaches))]
        [System.Xml.Serialization.XmlElementAttribute("country", typeof(country))]
        [System.Xml.Serialization.XmlElementAttribute("division", typeof(division))]
        [System.Xml.Serialization.XmlElementAttribute("economy", typeof(economy))]
        [System.Xml.Serialization.XmlElementAttribute("match", typeof(match))]
        //[System.Xml.Serialization.XmlElementAttribute("matches", typeof(matches))]
        [System.Xml.Serialization.XmlElementAttribute("player", typeof(player))]
        [System.Xml.Serialization.XmlElementAttribute("players", typeof(players))]
        //[System.Xml.Serialization.XmlElementAttribute("schedule", typeof(schedule))]
        [System.Xml.Serialization.XmlElementAttribute("team", typeof(team))]
        [System.Xml.Serialization.XmlElementAttribute("team_transfers", typeof(team_transfers))]
        [System.Xml.Serialization.XmlElementAttribute("user", typeof(user))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class arena {
        
        private string nameField;
        
        private uint idField;
        
        private uint spectatorsField;
        
        private uint vipsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint spectators {
            get {
                return this.spectatorsField;
            }
            set {
                this.spectatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint vips {
            get {
                return this.vipsField;
            }
            set {
                this.vipsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class myNtCoach {
        
        private user userField;
        
        private string botField;
        
        /// <remarks/>
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bot {
            get {
                return this.botField;
            }
            set {
                this.botField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class user {
        
        private string nameField;
        
        private uint idField;
        
        private string supporterField;
        
        private uint registeredField;
        
        private uint last_activeField;
        
        private uint teamidField;
        
        private byte countryidField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string supporter {
            get {
                return this.supporterField;
            }
            set {
                this.supporterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint registered {
            get {
                return this.registeredField;
            }
            set {
                this.registeredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint last_active {
            get {
                return this.last_activeField;
            }
            set {
                this.last_activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint teamid {
            get {
                return this.teamidField;
            }
            set {
                this.teamidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class coaches {
        
        private coach[] coachField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coach")]
        public coach[] coach {
            get {
                return this.coachField;
            }
            set {
                this.coachField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class coach {
        
        private basic basicField;
        
        private skills skillsField;
        
        private uint priceField;
        
        private uint salaryField;
        
        private uint idField;
        
        private byte countryidField;
        
        private uint teamidField;
        
        /// <remarks/>
        public basic basic {
            get {
                return this.basicField;
            }
            set {
                this.basicField = value;
            }
        }
        
        /// <remarks/>
        public skills skills {
            get {
                return this.skillsField;
            }
            set {
                this.skillsField = value;
            }
        }
        
        /// <remarks/>
        public uint price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public uint salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint teamid {
            get {
                return this.teamidField;
            }
            set {
                this.teamidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class basic {
        
        private string nameField;
        
        private string surnameField;
        
        private byte ageField;
        
        private byte heightField;
        
        private decimal weightField;
        
        private number numberField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public byte age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public byte height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public decimal weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public number number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class number {
        
        private string showField;
        
        private byte valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string show {
            get {
                return this.showField;
            }
            set {
                this.showField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public byte Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class skills {
        
        private byte defenceField;
        
        private byte freethrowField;
        
        private byte twopointField;
        
        private byte threepointField;
        
        private byte driblingField;
        
        private byte speedField;
        
        private byte footworkField;
        
        private byte reboundsField;
        
        private byte passingField;
        
        private byte experienceField;
        
        /// <remarks/>
        public byte defence {
            get {
                return this.defenceField;
            }
            set {
                this.defenceField = value;
            }
        }
        
        /// <remarks/>
        public byte freethrow {
            get {
                return this.freethrowField;
            }
            set {
                this.freethrowField = value;
            }
        }
        
        /// <remarks/>
        public byte twopoint {
            get {
                return this.twopointField;
            }
            set {
                this.twopointField = value;
            }
        }
        
        /// <remarks/>
        public byte threepoint {
            get {
                return this.threepointField;
            }
            set {
                this.threepointField = value;
            }
        }
        
        /// <remarks/>
        public byte dribling {
            get {
                return this.driblingField;
            }
            set {
                this.driblingField = value;
            }
        }
        
        /// <remarks/>
        public byte speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        public byte footwork {
            get {
                return this.footworkField;
            }
            set {
                this.footworkField = value;
            }
        }
        
        /// <remarks/>
        public byte rebounds {
            get {
                return this.reboundsField;
            }
            set {
                this.reboundsField = value;
            }
        }
        
        /// <remarks/>
        public byte passing {
            get {
                return this.passingField;
            }
            set {
                this.passingField = value;
            }
        }
        
        /// <remarks/>
        public byte experience {
            get {
                return this.experienceField;
            }
            set {
                this.experienceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class country {
        
        private string nameField;
        
        private string flagField;
        
        private division[] divisionField;
        
        private country_info country_infoField;
        
        private byte idField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("division")]
        public division[] division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        public country_info country_info {
            get {
                return this.country_infoField;
            }
            set {
                this.country_infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class division {
        
        private string nameField;
        
        private standing[] standingsField;
        
        private uint idField;
        
        private byte levelField;
        
        private ushort lhField;
        
        private byte countryidField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("standing", IsNullable=false)]
        public standing[] standings {
            get {
                return this.standingsField;
            }
            set {
                this.standingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort lh {
            get {
                return this.lhField;
            }
            set {
                this.lhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class standing {
        
        private byte playedField;
        
        private ushort points_madeField;
        
        private ushort points_againstField;
        
        private ushort pointsField;
        
        private byte winsField;
        
        private byte lossField;
        
        private byte positionField;
        
        private uint teamidField;
        
        private string nameField;
        
        private uint ownerField;
        
        /// <remarks/>
        public byte played {
            get {
                return this.playedField;
            }
            set {
                this.playedField = value;
            }
        }
        
        /// <remarks/>
        public ushort points_made {
            get {
                return this.points_madeField;
            }
            set {
                this.points_madeField = value;
            }
        }
        
        /// <remarks/>
        public ushort points_against {
            get {
                return this.points_againstField;
            }
            set {
                this.points_againstField = value;
            }
        }
        
        /// <remarks/>
        public ushort points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        public byte wins {
            get {
                return this.winsField;
            }
            set {
                this.winsField = value;
            }
        }
        
        /// <remarks/>
        public byte loss {
            get {
                return this.lossField;
            }
            set {
                this.lossField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint teamid {
            get {
                return this.teamidField;
            }
            set {
                this.teamidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class country_info {
        
        private ntcoach ntcoachField;
        
        private object u21ntcoachField;
        
        private object u18ntcoachField;
        
        private string activeField;
        
        private uint usersField;
        
        private uint teamsField;
        
        private uint waitingField;
        
        private uint supportersField;
        
        /// <remarks/>
        public ntcoach ntcoach {
            get {
                return this.ntcoachField;
            }
            set {
                this.ntcoachField = value;
            }
        }
        
        /// <remarks/>
        public object u21ntcoach {
            get {
                return this.u21ntcoachField;
            }
            set {
                this.u21ntcoachField = value;
            }
        }
        
        /// <remarks/>
        public object u18ntcoach {
            get {
                return this.u18ntcoachField;
            }
            set {
                this.u18ntcoachField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint teams {
            get {
                return this.teamsField;
            }
            set {
                this.teamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint waiting {
            get {
                return this.waitingField;
            }
            set {
                this.waitingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint supporters {
            get {
                return this.supportersField;
            }
            set {
                this.supportersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ntcoach {
        
        private user userField;
        
        private string botField;
        
        /// <remarks/>
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bot {
            get {
                return this.botField;
            }
            set {
                this.botField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class economy {
        
        private economy_week economy_weekField;
        
        private economy_season economy_seasonField;
        
        /// <remarks/>
        public economy_week economy_week {
            get {
                return this.economy_weekField;
            }
            set {
                this.economy_weekField = value;
            }
        }
        
        /// <remarks/>
        public economy_season economy_season {
            get {
                return this.economy_seasonField;
            }
            set {
                this.economy_seasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class economy_week {
        
        private income incomeField;
        
        private expences expencesField;
        
        /// <remarks/>
        public income income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
            }
        }
        
        /// <remarks/>
        public expences expences {
            get {
                return this.expencesField;
            }
            set {
                this.expencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class income {
        
        private uint sponsorField;
        
        private uint ticketsField;
        
        private uint salesField;
        
        private uint otherField;
        
        private uint merchandiseField;
        
        /// <remarks/>
        public uint sponsor {
            get {
                return this.sponsorField;
            }
            set {
                this.sponsorField = value;
            }
        }
        
        /// <remarks/>
        public uint tickets {
            get {
                return this.ticketsField;
            }
            set {
                this.ticketsField = value;
            }
        }
        
        /// <remarks/>
        public uint sales {
            get {
                return this.salesField;
            }
            set {
                this.salesField = value;
            }
        }
        
        /// <remarks/>
        public uint other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
            }
        }
        
        /// <remarks/>
        public uint merchandise {
            get {
                return this.merchandiseField;
            }
            set {
                this.merchandiseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class expences {
        
        private uint salaryField;
        
        private uint staffField;
        
        private uint buysField;
        
        private uint maintenanceField;
        
        private uint facilityField;
        
        private uint otherField;
        
        /// <remarks/>
        public uint salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
            }
        }
        
        /// <remarks/>
        public uint staff {
            get {
                return this.staffField;
            }
            set {
                this.staffField = value;
            }
        }
        
        /// <remarks/>
        public uint buys {
            get {
                return this.buysField;
            }
            set {
                this.buysField = value;
            }
        }
        
        /// <remarks/>
        public uint maintenance {
            get {
                return this.maintenanceField;
            }
            set {
                this.maintenanceField = value;
            }
        }
        
        /// <remarks/>
        public uint facility {
            get {
                return this.facilityField;
            }
            set {
                this.facilityField = value;
            }
        }
        
        /// <remarks/>
        public uint other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class economy_season {
        
        private income incomeField;
        
        private expences expencesField;
        
        /// <remarks/>
        public income income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
            }
        }
        
        /// <remarks/>
        public expences expences {
            get {
                return this.expencesField;
            }
            set {
                this.expencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class teams {
        
        private uint hometeamField;
        
        private string hometeamnameField;
        
        private uint awayteamField;
        
        private string awayteamnameField;
        
        /// <remarks/>
        public uint hometeam {
            get {
                return this.hometeamField;
            }
            set {
                this.hometeamField = value;
            }
        }
        
        /// <remarks/>
        public string hometeamname {
            get {
                return this.hometeamnameField;
            }
            set {
                this.hometeamnameField = value;
            }
        }
        
        /// <remarks/>
        public uint awayteam {
            get {
                return this.awayteamField;
            }
            set {
                this.awayteamField = value;
            }
        }
        
        /// <remarks/>
        public string awayteamname {
            get {
                return this.awayteamnameField;
            }
            set {
                this.awayteamnameField = value;
            }
        }
    }
    
  /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class stats {
        
        private home homeField;
        
        private away awayField;
        
        /// <remarks/>
        public home home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
            }
        }
        
        /// <remarks/>
        public away away {
            get {
                return this.awayField;
            }
            set {
                this.awayField = value;
            }
        }
    }
    */

  /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class home {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bball", typeof(bball))]
        [System.Xml.Serialization.XmlElementAttribute("first", typeof(first))]
        [System.Xml.Serialization.XmlElementAttribute("forth", typeof(forth))]
        [System.Xml.Serialization.XmlElementAttribute("rating", typeof(rating))]
        [System.Xml.Serialization.XmlElementAttribute("second", typeof(second))]
        [System.Xml.Serialization.XmlElementAttribute("third", typeof(third))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
  */

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class bball {
        
        private uint playeridField;
        
        private decimal bballsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint playerid {
            get {
                return this.playeridField;
            }
            set {
                this.playeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal bballs {
            get {
                return this.bballsField;
            }
            set {
                this.bballsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class first {
        
        private uint pgField;
        
        private uint sgField;
        
        private uint sfField;
        
        private uint pfField;
        
        private uint cField;
        
        /// <remarks/>
        public uint pg {
            get {
                return this.pgField;
            }
            set {
                this.pgField = value;
            }
        }
        
        /// <remarks/>
        public uint sg {
            get {
                return this.sgField;
            }
            set {
                this.sgField = value;
            }
        }
        
        /// <remarks/>
        public uint sf {
            get {
                return this.sfField;
            }
            set {
                this.sfField = value;
            }
        }
        
        /// <remarks/>
        public uint pf {
            get {
                return this.pfField;
            }
            set {
                this.pfField = value;
            }
        }
        
        /// <remarks/>
        public uint c {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class forth {
        
        private uint pgField;
        
        private uint sgField;
        
        private uint sfField;
        
        private uint pfField;
        
        private uint cField;
        
        /// <remarks/>
        public uint pg {
            get {
                return this.pgField;
            }
            set {
                this.pgField = value;
            }
        }
        
        /// <remarks/>
        public uint sg {
            get {
                return this.sgField;
            }
            set {
                this.sgField = value;
            }
        }
        
        /// <remarks/>
        public uint sf {
            get {
                return this.sfField;
            }
            set {
                this.sfField = value;
            }
        }
        
        /// <remarks/>
        public uint pf {
            get {
                return this.pfField;
            }
            set {
                this.pfField = value;
            }
        }
        
        /// <remarks/>
        public uint c {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class rating {
        
        private byte pointsField;
        
        private byte o_rebField;
        
        private byte d_rebField;
        
        private byte toField;
        
        private byte assistField;
        
        private byte blocksField;
        
        private byte stealsField;
        
        private byte foulsField;
        
        private byte ft_mField;
        
        private byte ft_aField;
        
        private byte pt2_mField;
        
        private byte pt2_aField;
        
        private byte pt3_mField;
        
        private byte pt3_aField;
        
        private byte pldField;
        
        private sbyte rtgField;
        
        private uint playeridField;
        
        private string nameField;
        
        /// <remarks/>
        public byte points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        public byte o_reb {
            get {
                return this.o_rebField;
            }
            set {
                this.o_rebField = value;
            }
        }
        
        /// <remarks/>
        public byte d_reb {
            get {
                return this.d_rebField;
            }
            set {
                this.d_rebField = value;
            }
        }
        
        /// <remarks/>
        public byte to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public byte assist {
            get {
                return this.assistField;
            }
            set {
                this.assistField = value;
            }
        }
        
        /// <remarks/>
        public byte blocks {
            get {
                return this.blocksField;
            }
            set {
                this.blocksField = value;
            }
        }
        
        /// <remarks/>
        public byte steals {
            get {
                return this.stealsField;
            }
            set {
                this.stealsField = value;
            }
        }
        
        /// <remarks/>
        public byte fouls {
            get {
                return this.foulsField;
            }
            set {
                this.foulsField = value;
            }
        }
        
        /// <remarks/>
        public byte ft_m {
            get {
                return this.ft_mField;
            }
            set {
                this.ft_mField = value;
            }
        }
        
        /// <remarks/>
        public byte ft_a {
            get {
                return this.ft_aField;
            }
            set {
                this.ft_aField = value;
            }
        }
        
        /// <remarks/>
        public byte pt2_m {
            get {
                return this.pt2_mField;
            }
            set {
                this.pt2_mField = value;
            }
        }
        
        /// <remarks/>
        public byte pt2_a {
            get {
                return this.pt2_aField;
            }
            set {
                this.pt2_aField = value;
            }
        }
        
        /// <remarks/>
        public byte pt3_m {
            get {
                return this.pt3_mField;
            }
            set {
                this.pt3_mField = value;
            }
        }
        
        /// <remarks/>
        public byte pt3_a {
            get {
                return this.pt3_aField;
            }
            set {
                this.pt3_aField = value;
            }
        }
        
        /// <remarks/>
        public byte pld {
            get {
                return this.pldField;
            }
            set {
                this.pldField = value;
            }
        }
        
        /// <remarks/>
        public sbyte rtg {
            get {
                return this.rtgField;
            }
            set {
                this.rtgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint playerid {
            get {
                return this.playeridField;
            }
            set {
                this.playeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class second {
        
        private uint pgField;
        
        private uint sgField;
        
        private uint sfField;
        
        private uint pfField;
        
        private uint cField;
        
        /// <remarks/>
        public uint pg {
            get {
                return this.pgField;
            }
            set {
                this.pgField = value;
            }
        }
        
        /// <remarks/>
        public uint sg {
            get {
                return this.sgField;
            }
            set {
                this.sgField = value;
            }
        }
        
        /// <remarks/>
        public uint sf {
            get {
                return this.sfField;
            }
            set {
                this.sfField = value;
            }
        }
        
        /// <remarks/>
        public uint pf {
            get {
                return this.pfField;
            }
            set {
                this.pfField = value;
            }
        }
        
        /// <remarks/>
        public uint c {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class third {
        
        private uint pgField;
        
        private uint sgField;
        
        private uint sfField;
        
        private uint pfField;
        
        private uint cField;
        
        /// <remarks/>
        public uint pg {
            get {
                return this.pgField;
            }
            set {
                this.pgField = value;
            }
        }
        
        /// <remarks/>
        public uint sg {
            get {
                return this.sgField;
            }
            set {
                this.sgField = value;
            }
        }
        
        /// <remarks/>
        public uint sf {
            get {
                return this.sfField;
            }
            set {
                this.sfField = value;
            }
        }
        
        /// <remarks/>
        public uint pf {
            get {
                return this.pfField;
            }
            set {
                this.pfField = value;
            }
        }
        
        /// <remarks/>
        public uint c {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
    }

    /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class away {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bball", typeof(bball))]
        [System.Xml.Serialization.XmlElementAttribute("first", typeof(first))]
        [System.Xml.Serialization.XmlElementAttribute("forth", typeof(forth))]
        [System.Xml.Serialization.XmlElementAttribute("rating", typeof(rating))]
        [System.Xml.Serialization.XmlElementAttribute("second", typeof(second))]
        [System.Xml.Serialization.XmlElementAttribute("third", typeof(third))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    */
    
    /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class bballs {
        
        private home homeField;
        
        private away awayField;
        
        /// <remarks/>
        public home home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
            }
        }
        
        /// <remarks/>
        public away away {
            get {
                return this.awayField;
            }
            set {
                this.awayField = value;
            }
        }
    }
    */
    
    /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class lineup {
        
        private home homeField;
        
        private away awayField;
        
        /// <remarks/>
        public home home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
            }
        }
        
        /// <remarks/>
        public away away {
            get {
                return this.awayField;
            }
            set {
                this.awayField = value;
            }
        }
    }
    */

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class player {
        
        private basic basicField;
        
        private skills skillsField;
        
        private status statusField;
        
        private uint idField;
        
        private string transferField;
        
        private string ntField;
        
        private string u21ntField;
        
        private string u18ntField;
        
        private uint promoted_onField;
        
        private string dlField;
        
        private byte countryidField;
        
        private uint teamidField;
        
        private byte traininggroupField;
        
        /// <remarks/>
        public basic basic {
            get {
                return this.basicField;
            }
            set {
                this.basicField = value;
            }
        }
        
        /// <remarks/>
        public skills skills {
            get {
                return this.skillsField;
            }
            set {
                this.skillsField = value;
            }
        }
        
        /// <remarks/>
        public status status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transfer {
            get {
                return this.transferField;
            }
            set {
                this.transferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nt {
            get {
                return this.ntField;
            }
            set {
                this.ntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string u21nt {
            get {
                return this.u21ntField;
            }
            set {
                this.u21ntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string u18nt {
            get {
                return this.u18ntField;
            }
            set {
                this.u18ntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint promoted_on {
            get {
                return this.promoted_onField;
            }
            set {
                this.promoted_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dl {
            get {
                return this.dlField;
            }
            set {
                this.dlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint teamid {
            get {
                return this.teamidField;
            }
            set {
                this.teamidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte traininggroup {
            get {
                return this.traininggroupField;
            }
            set {
                this.traininggroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class status {
        
        private byte injuredField;
        
        private byte fatigueField;
        
        private byte formField;
        
        private byte fameField;
        
        private uint siField;
        
        private uint salaryField;
        
        /// <remarks/>
        public byte injured {
            get {
                return this.injuredField;
            }
            set {
                this.injuredField = value;
            }
        }
        
        /// <remarks/>
        public byte fatigue {
            get {
                return this.fatigueField;
            }
            set {
                this.fatigueField = value;
            }
        }
        
        /// <remarks/>
        public byte form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
            }
        }
        
        /// <remarks/>
        public byte fame {
            get {
                return this.fameField;
            }
            set {
                this.fameField = value;
            }
        }
        
        /// <remarks/>
        public uint si {
            get {
                return this.siField;
            }
            set {
                this.siField = value;
            }
        }
        
        /// <remarks/>
        public uint salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class players {
        
        private player[] playerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("player")]
        public player[] player {
            get {
                return this.playerField;
            }
            set {
                this.playerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class round {
        
        private match matchField;
        
        private byte numberField;
        
        private uint dateField;
        
        /// <remarks/>
        public match match {
            get {
                return this.matchField;
            }
            set {
                this.matchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class team {
        
        private string nameField;
        
        private team_info team_infoField;
        
        private uint idField;
        
        private byte countryidField;
        
        private uint useridField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public team_info team_info {
            get {
                return this.team_infoField;
            }
            set {
                this.team_infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class team_info {
        
        private fanclub fanclubField;
        
        private training trainingField;
        
        private byte chemistryField;
        
        private uint divisionidField;
        
        private uint arenaidField;
        
        private uint rivalField;
        
        /// <remarks/>
        public fanclub fanclub {
            get {
                return this.fanclubField;
            }
            set {
                this.fanclubField = value;
            }
        }
        
        /// <remarks/>
        public training training {
            get {
                return this.trainingField;
            }
            set {
                this.trainingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte chemistry {
            get {
                return this.chemistryField;
            }
            set {
                this.chemistryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint divisionid {
            get {
                return this.divisionidField;
            }
            set {
                this.divisionidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint arenaid {
            get {
                return this.arenaidField;
            }
            set {
                this.arenaidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint rival {
            get {
                return this.rivalField;
            }
            set {
                this.rivalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fanclub {
        
        private string nameField;
        
        private byte moodField;
        
        private uint fansField;
        
        private byte levelField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte mood {
            get {
                return this.moodField;
            }
            set {
                this.moodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint fans {
            get {
                return this.fansField;
            }
            set {
                this.fansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class training {
        
        private string group1Field;
        
        private string group2Field;
        
        /// <remarks/>
        public string group1 {
            get {
                return this.group1Field;
            }
            set {
                this.group1Field = value;
            }
        }
        
        /// <remarks/>
        public string group2 {
            get {
                return this.group2Field;
            }
            set {
                this.group2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class team_transfers {
        
        private transfer[] transferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transfer")]
        public transfer[] transfer {
            get {
                return this.transferField;
            }
            set {
                this.transferField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class transfer {
        
        private uint sellteamField;
        
        private uint buyteamField;
        
        private uint playeridField;
        
        private uint dateField;
        
        private uint siField;
        
        private uint priceField;
        
        /// <remarks/>
        public uint sellteam {
            get {
                return this.sellteamField;
            }
            set {
                this.sellteamField = value;
            }
        }
        
        /// <remarks/>
        public uint buyteam {
            get {
                return this.buyteamField;
            }
            set {
                this.buyteamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint playerid {
            get {
                return this.playeridField;
            }
            set {
                this.playeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint si {
            get {
                return this.siField;
            }
            set {
                this.siField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class u21ntcoach {
        
        private user userField;
        
        private string botField;
        
        /// <remarks/>
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bot {
            get {
                return this.botField;
            }
            set {
                this.botField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class u18ntcoach {
        
        private user userField;
        
        private string botField;
        
        /// <remarks/>
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bot {
            get {
                return this.botField;
            }
            set {
                this.botField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class standings {
        
        private standing[] standingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("standing")]
        public standing[] standing {
            get {
                return this.standingField;
            }
            set {
                this.standingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class stats
    {

      private rating[] homeField;

      private rating[] awayField;

      /// <remarks/>
      [System.Xml.Serialization.XmlArrayItemAttribute("rating", IsNullable = false)]
      public rating[] home
      {
        get
        {
          return this.homeField;
        }
        set
        {
          this.homeField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlArrayItemAttribute("rating", IsNullable = false)]
      public rating[] away
      {
        get
        {
          return this.awayField;
        }
        set
        {
          this.awayField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class bballs
    {

      private bball[] homeField;

      private bball[] awayField;

      /// <remarks/>
      [System.Xml.Serialization.XmlArrayItemAttribute("bball", IsNullable = false)]
      public bball[] home
      {
        get
        {
          return this.homeField;
        }
        set
        {
          this.homeField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlArrayItemAttribute("bball", IsNullable = false)]
      public bball[] away
      {
        get
        {
          return this.awayField;
        }
        set
        {
          this.awayField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class lineup
    {

      private lineupHome homeField;

      private lineupAway awayField;

      /// <remarks/>
      public lineupHome home
      {
        get
        {
          return this.homeField;
        }
        set
        {
          this.homeField = value;
        }
      }

      /// <remarks/>
      public lineupAway away
      {
        get
        {
          return this.awayField;
        }
        set
        {
          this.awayField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class lineupHome
    {

      private first firstField;

      private second secondField;

      private third thirdField;

      private forth forthField;

      /// <remarks/>
      public first first
      {
        get
        {
          return this.firstField;
        }
        set
        {
          this.firstField = value;
        }
      }

      /// <remarks/>
      public second second
      {
        get
        {
          return this.secondField;
        }
        set
        {
          this.secondField = value;
        }
      }

      /// <remarks/>
      public third third
      {
        get
        {
          return this.thirdField;
        }
        set
        {
          this.thirdField = value;
        }
      }

      /// <remarks/>
      public forth forth
      {
        get
        {
          return this.forthField;
        }
        set
        {
          this.forthField = value;
        }
      }
    }

    /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class first
    {

      private uint pgField;

      private uint sgField;

      private uint sfField;

      private uint pfField;

      private uint cField;

      /// <remarks/>
      public uint pg
      {
        get
        {
          return this.pgField;
        }
        set
        {
          this.pgField = value;
        }
      }

      /// <remarks/>
      public uint sg
      {
        get
        {
          return this.sgField;
        }
        set
        {
          this.sgField = value;
        }
      }

      /// <remarks/>
      public uint sf
      {
        get
        {
          return this.sfField;
        }
        set
        {
          this.sfField = value;
        }
      }

      /// <remarks/>
      public uint pf
      {
        get
        {
          return this.pfField;
        }
        set
        {
          this.pfField = value;
        }
      }

      /// <remarks/>
      public uint c
      {
        get
        {
          return this.cField;
        }
        set
        {
          this.cField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class second
    {

      private uint pgField;

      private uint sgField;

      private uint sfField;

      private uint pfField;

      private uint cField;

      /// <remarks/>
      public uint pg
      {
        get
        {
          return this.pgField;
        }
        set
        {
          this.pgField = value;
        }
      }

      /// <remarks/>
      public uint sg
      {
        get
        {
          return this.sgField;
        }
        set
        {
          this.sgField = value;
        }
      }

      /// <remarks/>
      public uint sf
      {
        get
        {
          return this.sfField;
        }
        set
        {
          this.sfField = value;
        }
      }

      /// <remarks/>
      public uint pf
      {
        get
        {
          return this.pfField;
        }
        set
        {
          this.pfField = value;
        }
      }

      /// <remarks/>
      public uint c
      {
        get
        {
          return this.cField;
        }
        set
        {
          this.cField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class third
    {

      private uint pgField;

      private uint sgField;

      private uint sfField;

      private uint pfField;

      private uint cField;

      /// <remarks/>
      public uint pg
      {
        get
        {
          return this.pgField;
        }
        set
        {
          this.pgField = value;
        }
      }

      /// <remarks/>
      public uint sg
      {
        get
        {
          return this.sgField;
        }
        set
        {
          this.sgField = value;
        }
      }

      /// <remarks/>
      public uint sf
      {
        get
        {
          return this.sfField;
        }
        set
        {
          this.sfField = value;
        }
      }

      /// <remarks/>
      public uint pf
      {
        get
        {
          return this.pfField;
        }
        set
        {
          this.pfField = value;
        }
      }

      /// <remarks/>
      public uint c
      {
        get
        {
          return this.cField;
        }
        set
        {
          this.cField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class forth
    {

      private uint pgField;

      private uint sgField;

      private uint sfField;

      private uint pfField;

      private uint cField;

      /// <remarks/>
      public uint pg
      {
        get
        {
          return this.pgField;
        }
        set
        {
          this.pgField = value;
        }
      }

      /// <remarks/>
      public uint sg
      {
        get
        {
          return this.sgField;
        }
        set
        {
          this.sgField = value;
        }
      }

      /// <remarks/>
      public uint sf
      {
        get
        {
          return this.sfField;
        }
        set
        {
          this.sfField = value;
        }
      }

      /// <remarks/>
      public uint pf
      {
        get
        {
          return this.pfField;
        }
        set
        {
          this.pfField = value;
        }
      }

      /// <remarks/>
      public uint c
      {
        get
        {
          return this.cField;
        }
        set
        {
          this.cField = value;
        }
      }
    }
    */

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class lineupAway
    {

      private first firstField;

      private second secondField;

      private third thirdField;

      private forth forthField;

      /// <remarks/>
      public first first
      {
        get
        {
          return this.firstField;
        }
        set
        {
          this.firstField = value;
        }
      }

      /// <remarks/>
      public second second
      {
        get
        {
          return this.secondField;
        }
        set
        {
          this.secondField = value;
        }
      }

      /// <remarks/>
      public third third
      {
        get
        {
          return this.thirdField;
        }
        set
        {
          this.thirdField = value;
        }
      }

      /// <remarks/>
      public forth forth
      {
        get
        {
          return this.forthField;
        }
        set
        {
          this.forthField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class match
    {

      private teams teamsField;

      private stats statsField;

      private bballs bballsField;

      private lineup lineupField;

      private uint idField;

      private uint dateField;

      private bool dateFieldSpecified;

      private byte roundField;

      private bool roundFieldSpecified;

      private byte seasonField;

      private bool seasonFieldSpecified;

      private ushort spectatorsField;

      private bool spectatorsFieldSpecified;

      private ushort vipsField;

      private bool vipsFieldSpecified;

      private string playedField;

      private byte homescoreField;

      private bool homescoreFieldSpecified;

      private byte awayscoreField;

      private bool awayscoreFieldSpecified;

      private byte typeField;

      private bool typeFieldSpecified;

      private ushort leagueidField;

      private bool leagueidFieldSpecified;

      /// <remarks/>
      public teams teams
      {
        get
        {
          return this.teamsField;
        }
        set
        {
          this.teamsField = value;
        }
      }

      /// <remarks/>
      public stats stats
      {
        get
        {
          return this.statsField;
        }
        set
        {
          this.statsField = value;
        }
      }

      /// <remarks/>
      public bballs bballs
      {
        get
        {
          return this.bballsField;
        }
        set
        {
          this.bballsField = value;
        }
      }

      /// <remarks/>
      public lineup lineup
      {
        get
        {
          return this.lineupField;
        }
        set
        {
          this.lineupField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public uint id
      {
        get
        {
          return this.idField;
        }
        set
        {
          this.idField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public uint date
      {
        get
        {
          return this.dateField;
        }
        set
        {
          this.dateField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool dateSpecified
      {
        get
        {
          return this.dateFieldSpecified;
        }
        set
        {
          this.dateFieldSpecified = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public byte round
      {
        get
        {
          return this.roundField;
        }
        set
        {
          this.roundField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool roundSpecified
      {
        get
        {
          return this.roundFieldSpecified;
        }
        set
        {
          this.roundFieldSpecified = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public byte season
      {
        get
        {
          return this.seasonField;
        }
        set
        {
          this.seasonField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool seasonSpecified
      {
        get
        {
          return this.seasonFieldSpecified;
        }
        set
        {
          this.seasonFieldSpecified = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public ushort spectators
      {
        get
        {
          return this.spectatorsField;
        }
        set
        {
          this.spectatorsField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool spectatorsSpecified
      {
        get
        {
          return this.spectatorsFieldSpecified;
        }
        set
        {
          this.spectatorsFieldSpecified = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public ushort vips
      {
        get
        {
          return this.vipsField;
        }
        set
        {
          this.vipsField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool vipsSpecified
      {
        get
        {
          return this.vipsFieldSpecified;
        }
        set
        {
          this.vipsFieldSpecified = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string played
      {
        get
        {
          return this.playedField;
        }
        set
        {
          this.playedField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public byte homescore
      {
        get
        {
          return this.homescoreField;
        }
        set
        {
          this.homescoreField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool homescoreSpecified
      {
        get
        {
          return this.homescoreFieldSpecified;
        }
        set
        {
          this.homescoreFieldSpecified = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public byte awayscore
      {
        get
        {
          return this.awayscoreField;
        }
        set
        {
          this.awayscoreField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool awayscoreSpecified
      {
        get
        {
          return this.awayscoreFieldSpecified;
        }
        set
        {
          this.awayscoreFieldSpecified = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public byte type
      {
        get
        {
          return this.typeField;
        }
        set
        {
          this.typeField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool typeSpecified
      {
        get
        {
          return this.typeFieldSpecified;
        }
        set
        {
          this.typeFieldSpecified = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public ushort leagueid
      {
        get
        {
          return this.leagueidField;
        }
        set
        {
          this.leagueidField = value;
        }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool leagueidSpecified
      {
        get
        {
          return this.leagueidFieldSpecified;
        }
        set
        {
          this.leagueidFieldSpecified = value;
        }
      }
    }

    ///////////////////////////////////////////////////////////////////
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class matches
    {

      private match[] matchField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("match")]
      public match[] match
      {
        get
        {
          return this.matchField;
        }
        set
        {
          this.matchField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class schedule
    {

      private round[] roundField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("round")]
      public round[] round
      {
        get
        {
          return this.roundField;
        }
        set
        {
          this.roundField = value;
        }
      }
    }
}
